import type { RecommendationContextItem } from './recommendationContextItem';
import type { RecommendationMessageItem } from './recommendationMessageItem';

/**
 * Contains the AI recommendation, the retrieved context, and the persisted chat history used to build it.
 */
export interface AskRecommendationResponse {
  /** Persistent chat identifier stored in the database. */
  chat_id: string;
  /** Final recommendation generated by Gemini grounded on the retrieved context. */
  answer: string;
  /** Retrieved context entries returned by Chroma and used in the prompt. */
  contexts: RecommendationContextItem[];
  /** Ordered chat messages persisted for the current conversation. */
  messages: RecommendationMessageItem[];
}
