export type GetAllUsersSessionLogsOrderBy = (typeof GetAllUsersSessionLogsOrderBy)[keyof typeof GetAllUsersSessionLogsOrderBy];

export const GetAllUsersSessionLogsOrderBy = {
  id: 'id',
  username: 'username',
  displayName: 'displayName',
  isEmailVerified: 'isEmailVerified',
  lastLoginAt: 'lastLoginAt',
  roles: 'roles',
  rolesid: 'roles.id',
  rolesname: 'roles.name',
  picture: 'picture',
  pictureid: 'picture.id',
  pictureurl: 'picture.url',
  picturejobId: 'picture.jobId',
  pictureprocessing: 'picture.processing',
  pictureorigin: 'picture.origin',
  picturecreatedAt: 'picture.createdAt',
  pictureupdatedAt: 'picture.updatedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  email: 'email',
  sessionLogs: 'sessionLogs',
  sessionLogsid: 'sessionLogs.id',
  sessionLogssessionId: 'sessionLogs.sessionId',
  sessionLogsstatus: 'sessionLogs.status',
  sessionLogsfailureReason: 'sessionLogs.failureReason',
  sessionLogsipAddress: 'sessionLogs.ipAddress',
  sessionLogscountry: 'sessionLogs.country',
  sessionLogscity: 'sessionLogs.city',
  sessionLogsbrowser: 'sessionLogs.browser',
  sessionLogsos: 'sessionLogs.os',
  sessionLogsdeviceType: 'sessionLogs.deviceType',
  sessionLogsrevokedAt: 'sessionLogs.revokedAt',
  sessionLogscreatedAt: 'sessionLogs.createdAt',
} as const;
